Update main.tf
without this line terraform init woul fail with error
Error: Missing required argument
│ 
│   on main.tf line 17, in module "security_group":
│   17: module "security_group" {
│ 
│ The argument "vpc_id" is required, but no definition was found.